/** Sample data for Images → Internal tab. Replace with API. */

export const SAMPLE_IMAGES_INTERNAL = [
  {
    id: "1",
    url: "https://example.com/content/dam/examplemall-site/resources/icons/wishlist.gif",
    type: "Image",
    responseCode: "200",
    pages: 497,
  },
  {
    id: "2",
    url: "https://example.com/content/dam/examplemall-site/resources/icons/sheild-protect-verified.svg",
    type: "Image",
    responseCode: "200",
    pages: 497,
  },
  {
    id: "3",
    url: "https://example.com/content/dam/examplemall-site/resources/icons/proceed_now.gif",
    type: "Image",
    responseCode: "200",
    pages: 6,
  },
  {
    id: "4",
    url: "https://example.com/content/dam/examplemall-site/resources/icons/icon-play-desktop.svg",
    type: "Image",
    responseCode: "200",
    pages: 305,
  },
  {
    id: "5",
    url: "https://example.com/content/dam/examplemall-site/resources/icons/filter-comp/star-value-badge-rating.svg",
    type: "Image",
    responseCode: "200",
    pages: 265,
  },
  {
    id: "6",
    url: "https://example.com/content/dam/examplemall-site/resources/icons/filter-comp/Dropdown.svg",
    type: "Image",
    responseCode: "200",
    pages: 452,
  },
  {
    id: "7",
    url: "https://example.com/content/dam/examplemall-site/resources/icons/filter-comp/down_arrow.svg",
    type: "Image",
    responseCode: "200",
    pages: 497,
  },
  {
    id: "8",
    url: "https://example.com/content/dam/examplemall-site/resources/icons/exclamation-alert-warning.svg",
    type: "Image",
    responseCode: "200",
    pages: 497,
  },
  {
    id: "9",
    url: "https://example.com/content/dam/examplemall-site/resources/icons/icon-check.svg",
    type: "Image",
    responseCode: "200",
    pages: 497,
  },
  {
    id: "10",
    url: "https://example.com/content/dam/examplemall-site/resources/icons/logo.svg",
    type: "Image",
    responseCode: "200",
    pages: 497,
  },
  {
    id: "11",
    url: "https://cms-assets.example.com/is/image/examplefinance/hero-banner?scl=1&fmt=png-alpha",
    type: "Image",
    responseCode: "200",
    pages: 12,
  },
  {
    id: "12",
    url: "https://cms-assets.example.com/is/image/examplefinance/product-thumb?scl=1&fmt=png-alpha",
    type: "Image",
    responseCode: "200",
    pages: 89,
  },
];
